In [1]:
# %load __main__.py
from numpy import random

from network import network
from encoder import encoder as data

# Loading training and test sets
training_set, test_set = data.load()
print("Successfully loaded data. Initializing network...")

# Creating network
hidden_layers = [3]
x, y = training_set[0]
input_size = x.shape[0]
output_size = y.shape[0]

net = network(input_size, output_size, hidden_layers)
print("Successfully initialized network. Training network...")

for i in range(5):
    x, y = training_set[i]
    print("Result %i", i)
    print(net.forwardpass(x))
    print(y)

# Training variables
learning_rate = 1
set_size = 5
num_cycles = 1000

net.train(training_set, learning_rate, set_size, num_cycles)
print("Successfully trained network. Validating network...")

for i in range(5):
    x, y = training_set[i]
    print("Result %i", i)
    print(net.forwardpass(x))
    print(y)
    

# performance = data.validate(test_set, test_outputs)
# print(performance)

Successfully loaded data. Initializing network...
Successfully initialized network. Training network...
Result %i 0
[[ 0.88243998]
 [ 0.80184999]
 [ 0.82417666]
 [ 0.77052779]
 [ 0.93093957]]
[[ 1.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 0.]]
Result %i 1
[[ 0.87442643]
 [ 0.79348421]
 [ 0.81952666]
 [ 0.76549336]
 [ 0.92591734]]
[[ 0.]
 [ 1.]
 [ 0.]
 [ 0.]
 [ 0.]]
Result %i 2
[[ 0.89109411]
 [ 0.81699893]
 [ 0.82445897]
 [ 0.77188999]
 [ 0.9360356 ]]
[[ 0.]
 [ 0.]
 [ 1.]
 [ 0.]
 [ 0.]]
Result %i 3
[[ 0.88508016]
 [ 0.80784225]
 [ 0.82820306]
 [ 0.77110105]
 [ 0.93373704]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]
Result %i 4
[[ 0.87821166]
 [ 0.80412475]
 [ 0.82181303]
 [ 0.76430681]
 [ 0.9294546 ]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 0.]
 [ 1.]]
Successfully trained network. Validating network...
Result %i 0
[[ 0.18337222]
 [ 0.10139704]
 [ 0.03566135]
 [ 0.79000374]
 [ 0.13895473]]
[[ 0.]
 [ 0.]
 [ 0.]
 [ 1.]
 [ 0.]]
Result %i 1
[[ 0.04507535]
 [ 0.42019832]
 [ 0.14766216]
 [ 0.12635767]
 [ 0.42203795]]
[[ 0.]
 [ 0.