In [5]:
# %load __main__.py
from numpy import random

from network import network
from encoder import encoder as data

# Loading training and test sets
training_set, test_set = data.load()
print("Successfully loaded data. Initializing network...")

# Creating network
hidden_layers = [3]
x, y = training_set[0]
input_size = x.shape[0]
output_size = y.shape[0]

net = network(input_size, output_size, hidden_layers)
print("Successfully initialized network. Training network...")

# Training variables
learning_rate = 1
set_size = 1
num_cycles = 10000

net.train(training_set, learning_rate, set_size, num_cycles)
print("Successfully trained network. Validating network...")

test_outputs=[]

for i in range(len(test_set)):
    x, y = test_set[i]
    test_outputs.append(net.forwardpass(x))
    print(net.forwardpass(x, softmax=True))
    
performance = data.validate(test_set, test_outputs) * 100
print(performance)

Successfully loaded data. Initializing network...
Successfully initialized network. Training network...
Successfully trained network. Validating network...
[[  9.99305191e-01]
 [  1.67366203e-10]
 [  3.55254350e-04]
 [  1.58493887e-04]
 [  1.81060546e-04]]
[[  3.83146622e-14]
 [  9.99500484e-01]
 [  1.99376936e-04]
 [  2.16477794e-04]
 [  8.36614313e-05]]
[[  1.95696105e-04]
 [  8.61571148e-05]
 [  9.99718128e-01]
 [  5.02141498e-10]
 [  1.81203848e-08]]
[[  9.88299364e-05]
 [  6.07522817e-05]
 [  2.91180287e-10]
 [  9.99802444e-01]
 [  3.79735244e-05]]
[[  2.53003296e-04]
 [  1.63327085e-04]
 [  5.56829566e-08]
 [  9.16447036e-05]
 [  9.99491969e-01]]
100.0
